INSERT INTO Servicio (Nombre, DuracionAproximadaEnMinutos, Costo, Descripcion, TipoServicioID, Activo)
VALUES
    ('Ultrasonido abdominal completo', 45, 800, 'Evaluación completa de órganos abdominales en perros y gatos.', 13, 1),
    ('Ultrasonido hepático', 30, 600, 'Evaluación específica del hígado.', 13, 1),
    ('Ultrasonido renal', 30, 600, 'Evaluación de riñones para detectar anomalías.', 13, 1),
    ('Ultrasonido de vejiga', 25, 500, 'Evaluación de la vejiga urinaria.', 13, 1),
    ('Ultrasonido cardíaco', 60, 1000, 'Ecocardiografía para evaluar el corazón.', 13, 1),
    ('Ultrasonido de gestación', 40, 700, 'Confirmación y monitoreo de embarazo en hembras.', 13, 1),
    ('Ultrasonido de bazo', 30, 600, 'Evaluación del bazo para detectar masas o inflamación.', 13, 1),
    ('Ultrasonido gastrointestinal', 45, 800, 'Evaluación de estómago e intestinos.', 13, 1),
    ('Ultrasonido de páncreas', 30, 600, 'Evaluación del páncreas para detectar pancreatitis.', 13, 1),
    ('Ultrasonido de próstata', 25, 500, 'Evaluación de la próstata en machos no castrados.', 13, 1),
    ('Ultrasonido de útero', 30, 600, 'Evaluación del útero en hembras.', 13, 1),
    ('Ultrasonido de ovarios', 30, 600, 'Evaluación de ovarios en hembras no esterilizadas.', 13, 1),
    ('Ultrasonido de glándulas adrenales', 35, 650, 'Evaluación de glándulas adrenales.', 13, 1),
    ('Ultrasonido de tiroides', 25, 500, 'Evaluación de la glándula tiroides.', 13, 1),
    (N'Ultrasonido de ganglios linfáticos', 30, 600, 'Evaluación de ganglios linfáticos para inflamación o tumores.', 13, 1),
    ('Ultrasonido torácico', 50, 900, 'Evaluación de estructuras torácicas no cardíacas.', 13, 1),
    ('Ultrasonido de articulaciones', 40, 700, 'Evaluación de articulaciones para detectar lesiones.', 13, 1),
    ('Ultrasonido de ojos', 30, 600, 'Evaluación de estructuras oculares.', 13, 1),
    ('Ultrasonido de cuello', 35, 650, 'Evaluación de estructuras cervicales.', 13, 1),
    ('Ultrasonido de masas cutáneas', 25, 500, 'Evaluación de tumores o quistes subcutáneos.', 13, 1),
    ('Ultrasonido de hígado con Doppler', 45, 900, 'Evaluación del flujo sanguíneo hepático.', 13, 1),
    ('Ultrasonido renal con Doppler', 45, 900, 'Evaluación del flujo sanguíneo renal.', 13, 1),
    ('Ultrasonido de vesícula biliar', 30, 600, 'Evaluación de la vesícula biliar.', 13, 1),
    ('Ultrasonido de diafragma', 35, 650, 'Evaluación del diafragma para detectar hernias.', 13, 1),
    ('Ultrasonido de testículos', 25, 500, 'Evaluación de testículos en machos no castrados.', 13, 1),
    ('Ultrasonido de columna vertebral', 50, 900, 'Evaluación de la columna para detectar anomalías.', 13, 1),
    ('Ultrasonido de tráquea', 30, 600, 'Evaluación de la tráquea para detectar colapsos.', 13, 1),
    ('Ultrasonido de lengua', 25, 500, 'Evaluación de la lengua para detectar masas.', 13, 1),
    ('Ultrasonido de glándulas salivales', 30, 600, 'Evaluación de glándulas salivales.', 13, 1),
    ('Ultrasonido de pared abdominal', 35, 650, 'Evaluación de la pared abdominal para detectar hernias.', 13, 1);